CREATE TABLE APP_INTERLOCUTOR  (
   I_MOBILE             VARCHAR2(20) PRIMARY KEY,
   LAST_MESSAGE         VARCHAR2(300),
   LAST_TIME            DATETIME DEFAULT (datetime('now','localtime')),
   ISREADED             CHAR(1) DEFAULT '0'
);

CREATE TABLE APP_MESSAGE_LOG  (
   MSG_ID               INTEGER    PRIMARY KEY AUTOINCREMENT,
   SENDER_MOBILE        VARCHAR2(20),
   RECEIVER_MOBILE      VARCHAR2(20),
   MSG_CONTENT          VARCHAR2(300),
   MSG_TIME             DATETIME DEFAULT (datetime('now','localtime')),
   IMG_URL				VARCHAR2(200),
   VOICE_URL			VARCHAR2(200)
);