drop table APP_INTERLOCUTOR;
drop table APP_MESSAGE_LOG;

CREATE TABLE APP_INTERLOCUTOR  (
   MY_MOBILE            VARCHAR2(20) NOT NULL,  
   I_MOBILE             VARCHAR2(20) NOT NULL,
   LAST_MESSAGE         VARCHAR2(300),
   LAST_TIME            DATETIME DEFAULT (datetime('now','localtime')),
   ISREADED             CHAR(1) DEFAULT '0',
   CONSTRAINT PK_APP_INTERLOCUTOR PRIMARY KEY (MY_MOBILE, I_MOBILE)
);

CREATE TABLE APP_MESSAGE_LOG  (
   MSG_ID               INTEGER    PRIMARY KEY AUTOINCREMENT,
   SENDER_MOBILE        VARCHAR2(20),
   RECEIVER_MOBILE      VARCHAR2(20),
   MSG_CONTENT          VARCHAR2(300),
   MSG_TIME             DATETIME DEFAULT (datetime('now','localtime')),
   IMG_URL				VARCHAR2(200),
   VOICE_URL			VARCHAR2(200)
);